import Head from 'next/head';
import 'tailwindcss/tailwind.css';

import Navbar from '../components/Navbar.js';
import Button from '../components/Button';
import Footer from '../components/Footer';
import HomeSection from '../components/HomeSection';

export default function Home() {
    const DATABASE_ITEM = [
        {
            title: 'Tabung Oksigen',
            desc: 'Basis data pembelian, penyewaan, dan pengisian ulang tabung oksigen.',
            img: '/assets/database/oxygen.png'
        },
        // {
        //     title: 'Vaksinasi',
        //     desc: 'Coming Soon. ',
        //     img: '/assets/database/vaccine.png'
        // },
        {
            title: 'Tes Swab',
            desc: 'Basis data lokasi pelaksanaan tes usap (swab) antigen dan PCR. ',
            img: '/assets/database/swab.png'
        }
    ];

    const INFORMATION_ITEM = [
        {
            title: 'Indeks Kewaspadaan',
            desc: 'Informasi risiko COVID-19 di wilayah tertentu (via kawalcovid19.id). ',
            img: '/assets/information/map.png'
        },
        {
            title: 'Edukasi COVID-19',
            desc: 'Informasi tentang COVID-19. ',
            img: '/assets/information/covid.png'
        }
        // {
        //     title: 'Tanya Jawab',
        //     desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
        //     img: '/assets/information/info.png'
        // }
    ];

    return (
        <div className="flex-flex-col">
            <Navbar />
            <Head>
                <title>Indonesia Bebas Pandemi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />

                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                    rel="stylesheet"
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-col items-center mb-12">
                <div
                    className="flex flex-col items-center justify-center h-screen pb-24 px-8"
                    style={{ height: '56em' }}>
                    <div className="font-bold text-5xl mb-8 px-4 text-center">
                        Indonesia Bebas Pandemi
                    </div>
                    <p className="max-w-xl text-lg text-center">
                        Situs berbasis{' '}
                        <span className="italic font-semibold">
                            crowdsourcing
                        </span>{' '}
                        berisikan informasi dan basis data untuk membantu
                        masyarakat Indonesia menanggulangi pandemi COVID-19
                        (Coronavirus).
                    </p>
                    <div className="flex flex-row w-72 mt-4">
                        <Button className="mr-4">Basis Data</Button>
                        <Button>Informasi</Button>
                    </div>
                </div>

                <HomeSection
                    title="Basis Data"
                    className="mb-16"
                    items={DATABASE_ITEM}
                />
                <HomeSection title="Informasi" items={INFORMATION_ITEM} />
            </div>

            <Footer></Footer>
        </div>
    );
}
